# Generated by Django 6.1.1 on 2026-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiomassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_fish_count', models.IntegerField(default=250)),
                ('avg_fish_weight_kg', models.FloatField(default=0.00736)),
                ('feed_given_kg', models.FloatField()),
                ('fcr_value', models.FloatField()),
                ('cost_saved_idr', models.IntegerField()),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('catfish_count', models.IntegerField()),
                ('ph', models.FloatField()),
                ('temperature', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('tds', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
